-- =============================================================
-- ADMIN ACCOUNTS + SUBSCRIPTION APPROVAL FLOW
-- =============================================================
-- Run in Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.admin_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  gym_name TEXT NOT NULL,
  email TEXT NOT NULL,
  plan_type TEXT NOT NULL CHECK (plan_type IN ('monthly', 'six_months', 'yearly')),
  plan_price NUMERIC(12,2) NOT NULL,
  payment_status TEXT NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'approved', 'rejected')),
  approval_status TEXT NOT NULL DEFAULT 'pending' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
  is_active BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_accounts_user_id ON public.admin_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_admin_accounts_approval_status ON public.admin_accounts(approval_status);
CREATE INDEX IF NOT EXISTS idx_admin_accounts_payment_status ON public.admin_accounts(payment_status);

CREATE OR REPLACE FUNCTION public.set_updated_at_admin_accounts()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_admin_accounts_updated_at ON public.admin_accounts;
CREATE TRIGGER trg_admin_accounts_updated_at
BEFORE UPDATE ON public.admin_accounts
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_admin_accounts();

ALTER TABLE public.admin_accounts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'admin_accounts'
      AND policyname = 'admin_accounts_owner_read'
  ) THEN
    CREATE POLICY admin_accounts_owner_read
    ON public.admin_accounts
    FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'admin_accounts'
      AND policyname = 'admin_accounts_owner_insert'
  ) THEN
    CREATE POLICY admin_accounts_owner_insert
    ON public.admin_accounts
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'admin_accounts'
      AND policyname = 'admin_accounts_owner_update_limited'
  ) THEN
    CREATE POLICY admin_accounts_owner_update_limited
    ON public.admin_accounts
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- NOTE:
-- Super admin dashboard/policies for approving payments will be added later.
