-- ============================================
-- ENSURE COMPLETE GYM DATABASE (SAFE RUN)
-- ============================================
-- This script will create any missing tables without deleting existing data.
-- Run this in Supabase SQL Editor to ensure your database is complete.

-- 1. MEMBERS TABLE
CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    fee NUMERIC NOT NULL DEFAULT 3000,
    payment TEXT NOT NULL DEFAULT 'Unpaid',
    status TEXT NOT NULL DEFAULT 'Active',
    profile TEXT,
    join_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. ATTENDANCE TABLE
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    check_in_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(member_id, date)
);

-- 3. PAYMENTS TABLE (Critical for Annual Fee Report)
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE NOT NULL,
    amount NUMERIC DEFAULT 0,
    month_year TEXT NOT NULL, -- Format: 'YYYY-MM'
    status TEXT DEFAULT 'Paid', -- 'Paid' or 'Unpaid'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(member_id, month_year)
);

-- 4. CLASSES TABLE
CREATE TABLE IF NOT EXISTS public.classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    instructor TEXT NOT NULL,
    time TEXT NOT NULL,
    day TEXT NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 20,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. SUPPLEMENTS TABLE
CREATE TABLE IF NOT EXISTS public.supplements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE,
    supplement_type TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price NUMERIC NOT NULL,
    purchase_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. CARDIO SESSIONS TABLE
CREATE TABLE IF NOT EXISTS public.cardio_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE,
    session_type TEXT NOT NULL,
    duration INTEGER,
    calories_burned INTEGER,
    session_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. CARDIO SUBSCRIPTIONS TABLE
CREATE TABLE IF NOT EXISTS public.cardio_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE,
    duration TEXT NOT NULL,
    type TEXT NOT NULL,
    price NUMERIC NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    end_date TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. TRAINING PLANS TABLE
CREATE TABLE IF NOT EXISTS public.training_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE,
    plan_name TEXT NOT NULL,
    plan_type TEXT NOT NULL,
    trainer_name TEXT,
    goals TEXT[],
    start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    end_date TIMESTAMP WITH TIME ZONE,
    price NUMERIC NOT NULL,
    sessions_completed INTEGER DEFAULT 0,
    total_sessions INTEGER DEFAULT 12,
    notes TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. INVOICES TABLE
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE,
    invoice_number TEXT UNIQUE NOT NULL,
    amount NUMERIC NOT NULL,
    items JSONB,
    payment_method TEXT DEFAULT 'Cash',
    status TEXT DEFAULT 'Paid',
    issue_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    due_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. GYM SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.gym_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL UNIQUE,
    settings JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- INDEXES (Create if not exists)
-- ============================================

CREATE INDEX IF NOT EXISTS idx_members_name ON public.members(name);
CREATE INDEX IF NOT EXISTS idx_payments_member_month ON public.payments(member_id, month_year);
CREATE INDEX IF NOT EXISTS idx_attendance_member_date ON public.attendance(member_id, date);

-- ============================================
-- SECURITY POLICIES (Enable RLS)
-- ============================================

ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gym_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cardio_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_plans ENABLE ROW LEVEL SECURITY;

-- Simple "Allow All" policies for ease of use (You can restrict these later)

DO $$ 
BEGIN
    -- Members Policy
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'members' AND policyname = 'Allow all access members') THEN
        CREATE POLICY "Allow all access members" ON public.members FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Payments Policy
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'payments' AND policyname = 'Allow all access payments') THEN
        CREATE POLICY "Allow all access payments" ON public.payments FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Attendance Policy
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'attendance' AND policyname = 'Allow all access attendance') THEN
        CREATE POLICY "Allow all access attendance" ON public.attendance FOR ALL USING (true) WITH CHECK (true);
    END IF;
    
    -- Gym Settings Policy
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'gym_settings' AND policyname = 'Allow all access settings') THEN
        CREATE POLICY "Allow all access settings" ON public.gym_settings FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Subscriptions Policy
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'cardio_subscriptions' AND policyname = 'Allow all access cardio') THEN
        CREATE POLICY "Allow all access cardio" ON public.cardio_subscriptions FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Training Policy
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'training_plans' AND policyname = 'Allow all access training') THEN
        CREATE POLICY "Allow all access training" ON public.training_plans FOR ALL USING (true) WITH CHECK (true);
    END IF;

END $$;

-- ============================================
-- VERIFICATION
-- ============================================

SELECT 
    table_name, 
    (SELECT count(*) FROM information_schema.columns WHERE table_name = t.table_name) as columns
FROM information_schema.tables t
WHERE table_schema = 'public'
AND table_type = 'BASE TABLE';
