-- COMPLETE PAYMENTS TABLE SETUP
-- Run this in Supabase SQL Editor

-- 1. Create the table safely
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE NOT NULL,
    amount NUMERIC DEFAULT 0,
    month_year TEXT NOT NULL, -- Format: 'YYYY-MM' (e.g., '2024-01')
    status TEXT DEFAULT 'Paid',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(member_id, month_year)
);

-- 2. Create index for faster searching
CREATE INDEX IF NOT EXISTS idx_payments_member_month ON public.payments(member_id, month_year);

-- 3. Enable Security (RLS)
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- 4. Create Access Policy (Drop first to avoid errors if re-running)
DROP POLICY IF EXISTS "Allow all access" ON public.payments;

CREATE POLICY "Allow all access" 
ON public.payments 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- 5. Confirm creation
SELECT 'Table created successfully' as status, count(*) as total_records FROM public.payments;
