-- =============================================================
-- SUPABASE REQUIRED TABLES (APP-COMPATIBLE)
-- =============================================================
-- Safe to run multiple times.
-- Creates only tables needed by the current React app behavior.

-- -------------------------------------------------------------
-- Extensions
-- -------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -------------------------------------------------------------
-- Shared updated_at trigger
-- -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -------------------------------------------------------------
-- 1) members
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact TEXT,
  fee NUMERIC(12,2) NOT NULL DEFAULT 3000,
  payment TEXT NOT NULL DEFAULT 'Unpaid' CHECK (payment IN ('Paid', 'Unpaid')),
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  profile TEXT,
  join_date TIMESTAMPTZ DEFAULT now(),

  scoops_creatine INTEGER NOT NULL DEFAULT 0,
  scoops_whey INTEGER NOT NULL DEFAULT 0,
  scoops_preworkout INTEGER NOT NULL DEFAULT 0,
  cost_creatine NUMERIC(12,2) NOT NULL DEFAULT 0,
  cost_whey NUMERIC(12,2) NOT NULL DEFAULT 0,
  cost_preworkout NUMERIC(12,2) NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_members_updated_at ON public.members;
CREATE TRIGGER trg_members_updated_at
BEFORE UPDATE ON public.members
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -------------------------------------------------------------
-- 2) attendance
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  check_in_time TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (member_id, date)
);

-- -------------------------------------------------------------
-- 3) payments
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  month_year TEXT NOT NULL CHECK (month_year ~ '^\d{4}-\d{2}$'),
  amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Unpaid' CHECK (status IN ('Paid', 'Unpaid')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (member_id, month_year)
);

-- -------------------------------------------------------------
-- 4) classes
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  instructor TEXT NOT NULL,
  time TEXT NOT NULL,
  day TEXT NOT NULL,
  duration TEXT NOT NULL DEFAULT '60m',
  color TEXT NOT NULL DEFAULT 'orange',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_classes_updated_at ON public.classes;
CREATE TRIGGER trg_classes_updated_at
BEFORE UPDATE ON public.classes
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -------------------------------------------------------------
-- 5) gym_settings
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.gym_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL UNIQUE CHECK (category IN ('supplement', 'cardio', 'pt')),
  settings JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_gym_settings_updated_at ON public.gym_settings;
CREATE TRIGGER trg_gym_settings_updated_at
BEFORE UPDATE ON public.gym_settings
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -------------------------------------------------------------
-- 6) cardio_subscriptions
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cardio_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  duration TEXT NOT NULL CHECK (duration IN ('Weekly', 'Monthly')),
  type TEXT NOT NULL CHECK (type IN ('Standard', 'Unlimited')),
  price NUMERIC(12,2) NOT NULL,
  start_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  end_date TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Expired', 'Cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_cardio_subscriptions_updated_at ON public.cardio_subscriptions;
CREATE TRIGGER trg_cardio_subscriptions_updated_at
BEFORE UPDATE ON public.cardio_subscriptions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -------------------------------------------------------------
-- 7) training_plans
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.training_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  plan_name TEXT NOT NULL DEFAULT 'Personal Training',
  plan_type TEXT NOT NULL CHECK (plan_type IN ('one_month', 'six_months', 'one_year')),
  trainer_name TEXT,
  goals TEXT[],
  start_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  end_date TIMESTAMPTZ,
  price NUMERIC(12,2) NOT NULL,
  sessions_completed INTEGER NOT NULL DEFAULT 0,
  total_sessions INTEGER NOT NULL DEFAULT 12,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Completed', 'Cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_training_plans_updated_at ON public.training_plans;
CREATE TRIGGER trg_training_plans_updated_at
BEFORE UPDATE ON public.training_plans
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -------------------------------------------------------------
-- Helpful indexes
-- -------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_members_name ON public.members(name);
CREATE INDEX IF NOT EXISTS idx_members_status ON public.members(status);
CREATE INDEX IF NOT EXISTS idx_members_payment ON public.members(payment);

CREATE INDEX IF NOT EXISTS idx_attendance_member_date ON public.attendance(member_id, date);
CREATE INDEX IF NOT EXISTS idx_payments_member_month ON public.payments(member_id, month_year);
CREATE INDEX IF NOT EXISTS idx_classes_day_time ON public.classes(day, time);
CREATE INDEX IF NOT EXISTS idx_cardio_subscriptions_member_status ON public.cardio_subscriptions(member_id, status);
CREATE INDEX IF NOT EXISTS idx_training_plans_member_status ON public.training_plans(member_id, status);

-- -------------------------------------------------------------
-- Enable RLS
-- -------------------------------------------------------------
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gym_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cardio_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_plans ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- Idempotent RLS policies (authenticated users)
-- -------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'members' AND policyname = 'members_authenticated_all') THEN
    CREATE POLICY members_authenticated_all ON public.members FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'attendance' AND policyname = 'attendance_authenticated_all') THEN
    CREATE POLICY attendance_authenticated_all ON public.attendance FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'payments' AND policyname = 'payments_authenticated_all') THEN
    CREATE POLICY payments_authenticated_all ON public.payments FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'classes' AND policyname = 'classes_authenticated_all') THEN
    CREATE POLICY classes_authenticated_all ON public.classes FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'gym_settings' AND policyname = 'gym_settings_authenticated_all') THEN
    CREATE POLICY gym_settings_authenticated_all ON public.gym_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'cardio_subscriptions' AND policyname = 'cardio_subscriptions_authenticated_all') THEN
    CREATE POLICY cardio_subscriptions_authenticated_all ON public.cardio_subscriptions FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'training_plans' AND policyname = 'training_plans_authenticated_all') THEN
    CREATE POLICY training_plans_authenticated_all ON public.training_plans FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- -------------------------------------------------------------
-- Seed required settings rows (safe upsert)
-- -------------------------------------------------------------
INSERT INTO public.gym_settings (category, settings)
VALUES
  ('supplement', '{"creatine":{"price":100,"isAuto":true},"whey":{"price":300,"isAuto":true},"preworkout":{"price":200,"isAuto":true}}'::jsonb),
  ('cardio', '{"weeklyPrice":1000,"monthlyPrice":3000,"unlimitedMultiplier":1.5,"manualOverride":false}'::jsonb),
  ('pt', '{"rates":{"one_month":20000,"six_months":100000,"one_year":180000}}'::jsonb)
ON CONFLICT (category) DO NOTHING;

-- -------------------------------------------------------------
-- Quick verification
-- -------------------------------------------------------------
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
    'members',
    'attendance',
    'payments',
    'classes',
    'gym_settings',
    'cardio_subscriptions',
    'training_plans'
  )
ORDER BY table_name;
