-- =============================================================
-- UPGRADE SCRIPT: SYNC OLD APK DATABASE WITH PC SOFTWARE
-- =============================================================
-- Run this in your Supabase SQL Editor to support new features
-- WITHOUT deleting your existing members or attendance data.
-- =============================================================

-- 1. SaaS & ADMIN TABLES
CREATE TABLE IF NOT EXISTS public.software_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    price NUMERIC(12,2) NOT NULL,
    duration_months INTEGER NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO public.software_plans (name, slug, price, duration_months, description)
VALUES 
('Monthly Plan', 'monthly', 5000, 1, 'Standard monthly subscription'),
('Bi-Annual Plan', 'six_months', 25000, 6, 'Save 5000!'),
('Annual VIP Plan', 'yearly', 45000, 12, 'Best value!')
ON CONFLICT (slug) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.super_admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.admin_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    gym_name TEXT NOT NULL,
    plan_type TEXT NOT NULL CHECK (plan_type IN ('monthly', 'six_months', 'yearly')),
    plan_price NUMERIC(12,2) NOT NULL,
    payment_status TEXT NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'approved', 'rejected')),
    approval_status TEXT NOT NULL DEFAULT 'pending' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    is_active BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. OPERATIONAL TABLES (If missing)
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGSERIAL PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    owner_id UUID NOT NULL,
    amount NUMERIC DEFAULT 0,
    month_year TEXT NOT NULL,
    status TEXT DEFAULT 'Paid' CHECK (status IN ('Paid', 'Unpaid')),
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(member_id, month_year)
);

CREATE TABLE IF NOT EXISTS public.gym_settings (
    id BIGSERIAL PRIMARY KEY,
    owner_id UUID NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('supplement', 'cardio', 'pt', 'general')),
    settings JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(owner_id, category)
);

CREATE TABLE IF NOT EXISTS public.cardio_subscriptions (
    id BIGSERIAL PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE,
    owner_id UUID NOT NULL,
    duration TEXT NOT NULL CHECK (duration IN ('Weekly', 'Monthly')),
    type TEXT NOT NULL CHECK (type IN ('Standard', 'Unlimited')),
    price NUMERIC NOT NULL,
    start_date TIMESTAMPTZ DEFAULT now(),
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.training_plans (
    id BIGSERIAL PRIMARY KEY,
    member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE,
    owner_id UUID NOT NULL,
    plan_name TEXT NOT NULL,
    plan_type TEXT NOT NULL,
    trainer_name TEXT,
    price NUMERIC NOT NULL,
    start_date TIMESTAMPTZ DEFAULT now(),
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. UPDATING EXISTING TABLES (Adding owner_id if missing)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='owner_id') THEN
        ALTER TABLE public.members ADD COLUMN owner_id UUID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='owner_id') THEN
        ALTER TABLE public.attendance ADD COLUMN owner_id UUID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='classes' AND column_name='owner_id') THEN
        ALTER TABLE public.classes ADD COLUMN owner_id UUID;
    END IF;
END $$;

-- 4. RLS POLICIES (Simplified)
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gym_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Sync Policy" ON public.members;
CREATE POLICY "Sync Policy" ON public.members FOR ALL TO authenticated USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Sync Policy Attendance" ON public.attendance;
CREATE POLICY "Sync Policy Attendance" ON public.attendance FOR ALL TO authenticated USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

DROP POLICY IF EXISTS "Sync Policy Payments" ON public.payments;
CREATE POLICY "Sync Policy Payments" ON public.payments FOR ALL TO authenticated USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

-- =============================================================
-- UPGRADE COMPLETE! Your old database now supports the new app.
-- =============================================================
